## 1. Import Necessary Libraries

In [12]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

WARNING: Ignoring invalid distribution -otebook (c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -otebook (c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -otebook (c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (1.15.3)
Requirement already satisfied: numpy>=1.16.2 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (2.2.6)
Requirement already satisfied: pandas>=0.24.2 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (1.7.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=0.13.2 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from pandas>=0.24.2->mlxtend) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from pandas>=0.24.2->mlxtend) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -otebook (c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -otebook (c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -otebook (c:\users\abdul\appdata\local\programs\python\python310\lib\site-packages)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## 2. Import Dataset

In [14]:
online_retail_data = pd.read_excel("Online Retail.xlsx")
online_retail_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

## 3. Data Understanding

In [15]:
online_retail_data.shape

(541909, 8)

In [16]:
online_retail_data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [18]:
online_retail_data.describe(include="all")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909.0,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900.0,4070,4223,NaN,NaN,NaN,NaN,38
top,573585.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,1114.0,2313,2369,NaN,NaN,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570,NaN
min,NaN,NaN,NaN,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2011-03-28 11:34:00,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,2011-07-19 17:17:00,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,2011-10-19 11:27:00,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN

In [19]:
online_retail_data["Country"].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [20]:
online_retail_data["Country"].nunique()

38

### I want to find out the total transactions happened in each country

In [22]:
online_retail_data["Country"].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

### Let's build BEST ASSOCIATES for UK as it has more transactions

In [26]:
UK_data=online_retail_data[online_retail_data["Country"]=="United Kingdom"]
UK_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,15804.0,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,13113.0,United Kingdom
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,13113.0,United Kingdom
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113.0,United Kingdom
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,13113.0,United Kingdom

In [30]:
UK_data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133600
Country             0
dtype: int64

In [31]:
del UK_data["CustomerID"]

In [34]:
UK_data.dropna(inplace=True)

In [38]:
UK_pivot_data=pd.pivot_table( data= UK_data, values="Quantity", index="InvoiceNo", columns="Description",aggfunc="sum").fillna(0)
UK_pivot_data

Description,20713,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,wrongly coded 20713,wrongly coded 23343,wrongly coded-23343,wrongly marked,wrongly marked 23343,wrongly marked carton 22804,wrongly marked. 23343 in box,wrongly sold (22719) barcode,wrongly sold as sets,wrongly sold sets
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536366,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536367,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536369,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C581484,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C581490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C581499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C581568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
C581569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
UK_pivot_data_onehot=UK_pivot_data.applymap(lambda x:0 if x==0 else 1)
UK_pivot_data_onehot

Description,20713,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,wrongly coded 20713,wrongly coded 23343,wrongly coded-23343,wrongly marked,wrongly marked 23343,wrongly marked carton 22804,wrongly marked. 23343 in box,wrongly sold (22719) barcode,wrongly sold as sets,wrongly sold sets
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536369,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C581484,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C581490,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C581499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C581568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C581569,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## 4. Data Mining

In [29]:
from mlxtend.frequent_patterns import apriori,association_rules

In [50]:
freq_temsets=apriori(df=UK_pivot_data_onehot,min_support=0.02, use_colnames=True)
freq_temsets

      support                                           itemsets
0    0.038884                           (6 RIBBONS RUSTIC CHARM)
1    0.026497                  (60 CAKE CASES VINTAGE CHRISTMAS)
2    0.034483                      (60 TEATIME FAIRY CAKE CASES)
3    0.025363                   (72 SWEETHEART FAIRY CAKE CASES)
4    0.040563                       (ALARM CLOCK BAKELIKE GREEN)
..        ...                                                ...
242  0.021461  (RED HANGING HEART T-LIGHT HOLDER, WHITE HANGI...
243  0.020962  (STRAWBERRY CHARLOTTE BAG, RED RETROSPOT CHARL...
244  0.020962  (ROSES REGENCY TEACUP AND SAUCER , REGENCY CAK...
245  0.024183  (WOODEN PICTURE FRAME WHITE FINISH, WOODEN FRA...
246  0.022550  (ROSES REGENCY TEACUP AND SAUCER , PINK REGENC...

[247 rows x 2 columns]

In [52]:
best_associates=association_rules(df=freq_temsets,metric='confidence',min_threshold=0.02)
best_associates

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE GREEN),0.043512,0.040563,0.025817,0.593326,14.627420,1.0,0.024052,2.359232,0.974016,0.443146,0.576133,0.614896
1,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED ),0.040563,0.043512,0.025817,0.636465,14.627420,1.0,0.024052,2.631078,0.971022,0.443146,0.619928,0.614896
2,(CHARLOTTE BAG PINK POLKADOT),(RED RETROSPOT CHARLOTTE BAG),0.031352,0.041697,0.021915,0.698987,16.763518,1.0,0.020607,3.183593,0.970783,0.428571,0.685890,0.612279
3,(RED RETROSPOT CHARLOTTE BAG),(CHARLOTTE BAG PINK POLKADOT),0.041697,0.031352,0.021915,0.525571,16.763518,1.0,0.020607,2.041714,0.981262,0.428571,0.510216,0.612279
4,(CHARLOTTE BAG SUKI DESIGN),(RED RETROSPOT CHARLOTTE BAG),0.036933,0.041697,0.021688,0.587224,14.083142,1.0,0.020148,2.321603,0.964619,0.380876,0.569263,0.553677
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,"(ROSES REGENCY TEACUP AND SAUCER , GREEN REGEN...",(PINK REGENCY TEACUP AND SAUCER),0.032350,0.033303,0.022550,0.697055,20.930634,1.0,0.021473,3.190995,0.984058,0.523158,0.686618,0.687083
86,"(GREEN REGENCY TEACUP AND SAUCER, PINK REGENCY...",(ROSES REGENCY TEACUP AND SAUCER ),0.026543,0.045508,0.022550,0.849573,18.668575,1.0,0.021342,6.345201,0.972240,0.455545,0.842401,0.672543
87,(ROSES REGENCY TEACUP AND SAUCER ),"(GREEN REGENCY TEACUP AND SAUCER, PINK REGENCY...",0.045508,0.026543,0.022550,0.495513,18.668575,1.0,0.021342,1.929600,0.991558,0.455545,0.481758,0.672543
88,(PINK REGENCY TEACUP AND SAUCER),"(ROSES REGENCY TEACUP AND SAUCER , GREEN REGEN...",0.033303,0.032350,0.022550,0.677112,20.930634,1.0,0.021473,2.996856,0.985028,0.523158,0.666317,0.687083
89,(GREEN REGENCY TEACUP AND SAUCER),"(ROSES REGENCY TEACUP AND SAUCER , PINK REGENC...",0.044011,0.025272,0.022550,0.512371,20.274075,1.0,0.021438,1.998913,0.994442,0.482524,0.499728,0.702326

In [53]:
best_associates.to_csv("best_anticidents_consquents.csv")

# THE END