In [1]:
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier,RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
from sklearn.feature_selection import SelectFromModel,RFE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import warnings
warnings.filterwarnings("ignore")

In [2]:
credit_card_data=pd.read_csv("credit_card_clean.csv")
credit_card_data

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000.0,female,university,married,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,female,university,single,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,female,university,single,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,female,university,married,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,male,university,married,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,male,highschool,married,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,male,highschool,single,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,male,university,single,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,male,highschool,married,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,male,university,married,46,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [3]:
credit_card_data=credit_card_data.drop(columns="EDUCATION")

In [4]:
credit_card_data.dtypes

ID             int64
LIMIT_BAL    float64
SEX           object
MARRIAGE      object
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

In [5]:
Label_encoder=LabelEncoder()

In [6]:
credit_card_data.isna().sum()

ID           0
LIMIT_BAL    0
SEX          0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [7]:
credit_card_data["SEX"]=Label_encoder.fit_transform(credit_card_data["SEX"])
credit_card_data["MARRIAGE"]=Label_encoder.fit_transform(credit_card_data["MARRIAGE"])
credit_card_data

,ID,LIMIT_BAL,SEX,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000.0,0,0,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,0,2,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,0,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,0,0,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,0,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,1,0,39,0,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,1,2,43,-1,-1,-1,-1,0,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,1,2,37,4,3,2,-1,0,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,1,0,41,1,-1,0,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,1,0,46,0,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [8]:
del credit_card_data["ID"]
credit_card_data

,LIMIT_BAL,SEX,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000.0,0,0,24,2,2,-1,-1,-2,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,0,2,26,-1,2,0,0,0,2,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,0,2,34,0,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,0,0,37,0,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,0,57,-1,0,-1,0,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,0,39,0,0,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,150000.0,1,2,43,-1,-1,-1,-1,0,0,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,30000.0,1,2,37,4,3,2,-1,0,0,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,80000.0,1,0,41,1,-1,0,0,0,-1,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,50000.0,1,0,46,0,0,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [9]:
X=credit_card_data.drop("DEFAULT",axis=1)
y=credit_card_data["DEFAULT"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.20, random_state=123,shuffle=True,stratify=y)

In [11]:
rf_model=RandomForestClassifier(max_depth=5,)
rf_model.fit(X_train,y_train)
y_pred=rf_model.predict(X_test)
print("accuracy_score   :",accuracy_score(y_test,y_pred))
print("precision_score  :",precision_score(y_test,y_pred))
print("recall_score     :",recall_score(y_test,y_pred))
print("confusion_matrix :\n ",confusion_matrix(y_test,y_pred))

accuracy_score   : 0.8151666666666667
precision_score  : 0.698905109489051
recall_score     : 0.2886209495101733
confusion_matrix :
  [[4508  165]
 [ 944  383]]

In [12]:
rf_model.feature_importances_

array([2.21169578e-02, 2.91031133e-04, 6.03352538e-04, 3.88489505e-03,
       3.31013796e-01, 1.74448255e-01, 1.32982887e-01, 8.32483984e-02,
       5.68940656e-02, 3.58164767e-02, 1.37956982e-02, 7.79135859e-03,
       8.42319180e-03, 7.57108436e-03, 6.32622519e-03, 5.30322799e-03,
       4.14367502e-02, 2.12082437e-02, 1.62761481e-02, 1.52502919e-02,
       8.44392571e-03, 6.87373951e-03])

In [13]:
select_from_model=SelectFromModel(estimator=RandomForestClassifier(),max_features=15)
select_from_model.fit(X_train,y_train)

SelectFromModel(estimator=RandomForestClassifier(), max_features=15)

In [14]:
select_from_model.get_support()

array([ True, False, False,  True,  True,  True, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True])

In [15]:
len(select_from_model.get_support())

22

In [16]:
X.columns[select_from_model.get_support()]

Index(['LIMIT_BAL', 'AGE', 'PAY_1', 'PAY_2', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT6'],
      dtype='object')

In [17]:
X_train_pred_SFM = select_from_model.transform(X_train)
X_test_pred_SFM = select_from_model.transform(X_test)

In [18]:
def runRandomForest(X_train, X_test, y_train, y_test):
    rf_model=RandomForestClassifier(max_depth=5,)
    rf_model.fit(X_train,y_train)
    y_pred=rf_model.predict(X_test)
    print("accuracy_score   :",accuracy_score(y_test,y_pred))
    print("precision_score  :",precision_score(y_test,y_pred))
    print("recall_score     :",recall_score(y_test,y_pred))
    print("confusion_matrix :\n ",confusion_matrix(y_test,y_pred))

In [25]:
%%time
runRandomForest(X_train, X_test, y_train, y_test)

accuracy_score   : 0.8135
precision_score  : 0.696969696969697
recall_score     : 0.2773172569706104
confusion_matrix :
  [[4513  160]
 [ 959  368]]
CPU times: total: 1.75 s
Wall time: 1.75 s

In [26]:
%%time
runRandomForest(X_train_pred_SFM, X_test_pred_SFM, y_train, y_test)

accuracy_score   : 0.8228333333333333
precision_score  : 0.7237288135593221
recall_score     : 0.32177844762622454
confusion_matrix :
  [[4510  163]
 [ 900  427]]
CPU times: total: 1.72 s
Wall time: 1.72 s

In [21]:
rfe_model=RFE(estimator=RandomForestClassifier(), n_features_to_select=12)
rfe_model.fit(X_train,y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=12)

In [27]:
rfe_model.get_support()

array([ True, False, False,  True,  True,  True, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False])

In [28]:
X.columns[rfe_model.get_support()]

Index(['LIMIT_BAL', 'AGE', 'PAY_1', 'PAY_2', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2'],
      dtype='object')

In [29]:
X_train_pred_rfe=rfe_model.transform(X_train)
X_test_pred_rfe=rfe_model.transform(X_test)

In [30]:
%%time
runRandomForest(X_train, X_test, y_train, y_test )

accuracy_score   : 0.8141666666666667
precision_score  : 0.7038461538461539
recall_score     : 0.27581009796533534
confusion_matrix :
  [[4519  154]
 [ 961  366]]
CPU times: total: 1.78 s
Wall time: 1.77 s

In [31]:
%%time
runRandomForest(X_train_pred_rfe, X_test_pred_rfe, y_train, y_test )

accuracy_score   : 0.8215
precision_score  : 0.7191780821917808
recall_score     : 0.3165033911077619
confusion_matrix :
  [[4509  164]
 [ 907  420]]
CPU times: total: 1.72 s
Wall time: 1.72 s

In [32]:
rfe_model=RFE(estimator=GradientBoostingClassifier(max_depth=3), n_features_to_select=12)
rfe_model.fit(X_train,y_train)

RFE(estimator=GradientBoostingClassifier(), n_features_to_select=12)

In [33]:
rfe_model.get_support()

array([ True, False, False, False,  True,  True,  True,  True, False,
        True,  True, False,  True, False, False, False,  True,  True,
        True,  True, False, False])

In [34]:
X.columns[rfe_model.get_support()]

Index(['LIMIT_BAL', 'PAY_1', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_6', 'BILL_AMT1',
       'BILL_AMT3', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4'],
      dtype='object')

In [35]:
X_train_pred_rfe=rfe_model.transform(X_train)
X_test_pred_rfe=rfe_model.transform(X_test)

In [36]:
%%time
runRandomForest(X_train, X_test, y_train, y_test )

accuracy_score   : 0.8208333333333333
precision_score  : 0.7
recall_score     : 0.33232856066315
confusion_matrix :
  [[4484  189]
 [ 886  441]]
CPU times: total: 1.72 s
Wall time: 1.74 s

In [37]:
%%time
runRandomForest(X_train_pred_rfe, X_test_pred_rfe, y_train, y_test )

accuracy_score   : 0.821
precision_score  : 0.6913767019667171
recall_score     : 0.3443858327053504
confusion_matrix :
  [[4469  204]
 [ 870  457]]
CPU times: total: 1.25 s
Wall time: 1.3 s

In [38]:
for i in range(1,22):
    rfe_model=RFE(estimator=GradientBoostingClassifier(), n_features_to_select=i)
    rfe_model.fit(X_train,y_train)
    X_train_pred_rfe=rfe_model.transform(X_train)
    X_test_pred_rfe=rfe_model.transform(X_test)
    print("selected feature",i)
    runRandomForest(X_train_pred_rfe, X_test_pred_rfe, y_train, y_test)
    print("=================================")

selected feature 1
accuracy_score   : 0.8215
precision_score  : 0.7140468227424749
recall_score     : 0.32177844762622454
confusion_matrix :
  [[4502  171]
 [ 900  427]]
=================================
selected feature 2
accuracy_score   : 0.822
precision_score  : 0.714759535655058
recall_score     : 0.32479276563677467
confusion_matrix :
  [[4501  172]
 [ 896  431]]
=================================
selected feature 3
accuracy_score   : 0.8213333333333334
precision_score  : 0.717948717948718
recall_score     : 0.3165033911077619
confusion_matrix :
  [[4508  165]
 [ 907  420]]
=================================
selected feature 4
accuracy_score   : 0.823
precision_score  : 0.7204658901830283
recall_score     : 0.3262999246420497
confusion_matrix :
  [[4505  168]
 [ 894  433]]
=================================
selected feature 5
accuracy_score   : 0.8223333333333334
precision_score  : 0.719327731092437
recall_score     : 0.3225320271288621
confusion_matrix :
  [[4506  167]
 [ 899  428]]
=================================
selected feature 6
accuracy_score   : 0.8225
precision_score  : 0.7126623376623377
recall_score     : 0.3308214016578749
confusion_matrix :
  [[4496  177]
 [ 888  439]]
=================================
selected feature 7
accuracy_score   : 0.8226666666666667
precision_score  : 0.7051482059282371
recall_score     : 0.34061793519216277
confusion_matrix :
  [[4484  189]
 [ 875  452]]
=================================
selected feature 8
accuracy_score   : 0.8231666666666667
precision_score  : 0.696165191740413
recall_score     : 0.3556895252449133
confusion_matrix :
  [[4467  206]
 [ 855  472]]
=================================
selected feature 9
accuracy_score   : 0.8235
precision_score  : 0.7012012012012012
recall_score     : 0.3519216277317257
confusion_matrix :
  [[4474  199]
 [ 860  467]]
=================================
selected feature 10
accuracy_score   : 0.8218333333333333
precision_score  : 0.6942771084337349
recall_score     : 0.3474001507159005
confusion_matrix :
  [[4470  203]
 [ 866  461]]
=================================
selected feature 11
accuracy_score   : 0.8218333333333333
precision_score  : 0.6972477064220184
recall_score     : 0.3436322532027129
confusion_matrix :
  [[4475  198]
 [ 871  456]]
=================================
selected feature 12
accuracy_score   : 0.8228333333333333
precision_score  : 0.7012195121951219
recall_score     : 0.346646571213263
confusion_matrix :
  [[4477  196]
 [ 867  460]]
=================================
selected feature 13
accuracy_score   : 0.822
precision_score  : 0.6965098634294385
recall_score     : 0.3458929917106255
confusion_matrix :
  [[4473  200]
 [ 868  459]]
=================================
selected feature 14
accuracy_score   : 0.818
precision_score  : 0.6994906621392191
recall_score     : 0.31047475508666167
confusion_matrix :
  [[4496  177]
 [ 915  412]]
=================================
selected feature 15
accuracy_score   : 0.8173333333333334
precision_score  : 0.6915422885572139
recall_score     : 0.3142426525998493
confusion_matrix :
  [[4487  186]
 [ 910  417]]
=================================
selected feature 16
accuracy_score   : 0.822
precision_score  : 0.6965098634294385
recall_score     : 0.3458929917106255
confusion_matrix :
  [[4473  200]
 [ 868  459]]
=================================
selected feature 17
accuracy_score   : 0.8198333333333333
precision_score  : 0.694620253164557
recall_score     : 0.3308214016578749
confusion_matrix :
  [[4480  193]
 [ 888  439]]
=================================
selected feature 18
accuracy_score   : 0.8218333333333333
precision_score  : 0.6960486322188449
recall_score     : 0.34513941220798794
confusion_matrix :
  [[4473  200]
 [ 869  458]]
=================================
selected feature 19
accuracy_score   : 0.8151666666666667
precision_score  : 0.6953405017921147
recall_score     : 0.292388847023361
confusion_matrix :
  [[4503  170]
 [ 939  388]]
=================================
selected feature 20
accuracy_score   : 0.8143333333333334
precision_score  : 0.6865148861646234
recall_score     : 0.29540316503391106
confusion_matrix :
  [[4494  179]
 [ 935  392]]
=================================
selected feature 21
accuracy_score   : 0.8148333333333333
precision_score  : 0.7
recall_score     : 0.2848530519969857
confusion_matrix :
  [[4511  162]
 [ 949  378]]
=================================

# THE END